package ar.edu.utn.dds.k3003.app;

public enum SubState {
    START,

    WAITING_RESPONSE_OPTION,
    WAITING_RESPONSE_FORM_COLABORAR,

     WAITING_RESPONSE_STATION,
   QRVIANDADEPOSITAR,
    IDHELADERADEPOSITAR,
    QRVIANDARETIRAR,
    IDHELADERARETIRAR,
    COLABORADORID,
    CREARVIANDA,
    IDHELADERAINCIDENCIA,
    IDREPARAR, IDHELADERAVERINCIDENCIAS,
    AGREGARRUTA,
    IDHELADERADESTINO
}
